import type { Area } from "./types";

export type ModuleLayout = "directory" | "board" | "content" | "connection" | "journey";
export interface ModuleSpec {
  area: Area;
  slug: string;
  title: string;
  group: string;
  icon: string;
  description: string;
  prd: string;
  layout: ModuleLayout;
  fields: [string, string];
  samples: string[];
  steps: string[];
  action?: string | undefined;
}

const modules: ModuleSpec[] = [];
function add(
  area: Area,
  slug: string,
  title: string,
  group: string,
  icon: string,
  description: string,
  prd: string,
  layout: ModuleLayout,
  fields: [string, string],
  samples: string[],
  steps: string[],
  action?: string,
) {
  modules.push({
    area,
    slug,
    title,
    group,
    icon,
    description,
    prd,
    layout,
    fields,
    samples,
    steps,
    action,
  });
}

add(
  "super-admin",
  "medicos",
  "Médicos",
  "Rede",
  "doctors",
  "Profissionais, identificação e vínculos com as clínicas.",
  "3.1, 12.2",
  "directory",
  ["Profissional", "Clínicas vinculadas"],
  ["Profissional de demonstração A", "Profissional de demonstração B"],
  ["Identificação", "Verificação de CRM", "Vínculo autorizado"],
);
add(
  "super-admin",
  "clientes",
  "Clientes",
  "Rede",
  "users",
  "Uma visão administrativa da rede, sem acesso automático ao conteúdo clínico.",
  "12.3",
  "directory",
  ["Cliente", "Situação administrativa"],
  ["Cliente de demonstração A", "Cliente de demonstração B"],
  ["Cadastro", "Plano e vínculo", "Acompanhamento administrativo"],
);
add(
  "super-admin",
  "planos",
  "Planos",
  "Comercial",
  "plans",
  "Organize o catálogo-base de serviços e suas condições.",
  "13",
  "content",
  ["Nome do plano", "Serviços previstos"],
  ["Catálogo de telemedicina", "Catálogo de dispositivos"],
  ["Serviços", "Condições aprovadas", "Disponibilidade para clínicas"],
  "Explorar plano",
);
add(
  "super-admin",
  "loja",
  "Loja central",
  "Comercial",
  "sales",
  "Produtos e serviços que poderão compor a oferta das clínicas.",
  "9.1",
  "content",
  ["Produto ou serviço", "Descrição da oferta"],
  ["Serviço de demonstração", "Produto de demonstração"],
  ["Catálogo central", "Disponibilização", "Operação comercial"],
  "Explorar produto",
);
add(
  "super-admin",
  "financeiro",
  "Financeiro",
  "Comercial",
  "finance",
  "Acompanhe competências, vidas habilitadas e fechamento.",
  "12.4, 14",
  "journey",
  ["Competência", "Resumo"],
  [],
  ["Vidas habilitadas", "Apuração", "Revisão", "Fechamento"],
);
add(
  "super-admin",
  "dispositivos",
  "Pulseiras",
  "Operação",
  "devices",
  "Estoque, identificação, expedição e vínculo de dispositivos.",
  "25–26",
  "connection",
  ["Dispositivo", "Identificação"],
  [],
  ["Cadastro", "Estoque", "Expedição", "Vínculo e monitoramento"],
);
add(
  "super-admin",
  "bioimpedancia",
  "Bioimpedância",
  "Operação",
  "activity",
  "Balanças, identificação e acompanhamento da integração.",
  "27–28",
  "connection",
  ["Balança", "Local de uso"],
  [],
  ["Modelo aprovado", "Identificação", "Integração", "Histórico"],
);
add(
  "super-admin",
  "blog",
  "Blog central",
  "Conteúdo",
  "book",
  "Conteúdo editorial compartilhado com as clínicas.",
  "15",
  "content",
  ["Título editorial", "Resumo editorial"],
  ["Conteúdo de boas-vindas", "Apresentação da plataforma"],
  ["Rascunho", "Revisão", "Publicação"],
  "Explorar artigo",
);
add(
  "super-admin",
  "academy",
  "Academy",
  "Conteúdo",
  "graduation",
  "Organize a capacitação e os materiais para as clínicas.",
  "16",
  "content",
  ["Nome da trilha", "Objetivo da trilha"],
  ["Primeiros passos da clínica", "Conhecendo a plataforma"],
  ["Conteúdo", "Revisão", "Disponibilização"],
  "Explorar trilha",
);
add(
  "super-admin",
  "inovacoes",
  "Central de inovação",
  "Plataforma",
  "sparkles",
  "Simulador, funcionamento, implantação guiada e qualidade da IA.",
  "29, 33",
  "content",
  ["Área", "Objetivo"],
  [
    "Simulador de rentabilidade",
    "Central de funcionamento",
    "Implantação guiada",
    "Laboratório de qualidade da IA",
  ],
  ["Premissas e critérios", "Configuração", "Validação", "Disponibilização"],
);
add(
  "super-admin",
  "privacidade",
  "Privacidade e acesso",
  "Plataforma",
  "shield",
  "Estrutura para acompanhamento de acessos e solicitações.",
  "4, 31.5",
  "journey",
  ["Solicitação", "Escopo"],
  [],
  ["Solicitação", "Verificação de identidade", "Análise autorizada", "Resposta"],
);

add(
  "clinica",
  "pacientes",
  "Pacientes",
  "Atendimento",
  "users",
  "Cadastro administrativo e organização do acompanhamento.",
  "3.5, 12.3",
  "directory",
  ["Paciente", "Vínculo com a clínica"],
  ["Paciente de demonstração A", "Paciente de demonstração B"],
  ["Cadastro", "Vínculo", "Agenda", "Acompanhamento"],
);
add(
  "clinica",
  "equipe",
  "Equipe",
  "Atendimento",
  "doctors",
  "Profissionais e responsabilidades da clínica.",
  "12.2, 23.1",
  "directory",
  ["Integrante", "Responsabilidade"],
  ["Equipe de atendimento", "Equipe administrativa"],
  ["Convite", "Identificação", "Permissões aprovadas"],
);
add(
  "clinica",
  "planos-produtos",
  "Planos & Produtos",
  "Comercial",
  "plans",
  "Componha ofertas a partir do catálogo disponível.",
  "9.2, 20",
  "content",
  ["Oferta", "Composição"],
  ["Oferta de demonstração A", "Oferta de demonstração B"],
  ["Catálogo disponível", "Composição", "Condições", "Oferta"],
  "Explorar oferta",
);
add(
  "clinica",
  "crm",
  "CRM de vendas",
  "Comercial",
  "users",
  "Organize oportunidades e os próximos contatos.",
  "21",
  "board",
  ["Oportunidade", "Próxima ação"],
  ["Oportunidade de demonstração A", "Oportunidade de demonstração B"],
  ["Entrada", "Em acompanhamento", "Concluído"],
  "Explorar oportunidade",
);
add(
  "clinica",
  "vendas",
  "Vendas",
  "Comercial",
  "sales",
  "Acompanhe ofertas, atribuição e histórico comercial.",
  "9.3, 23.2",
  "directory",
  ["Oferta", "Responsável"],
  ["Oferta em revisão", "Contato de demonstração"],
  ["Oferta", "Adesão", "Confirmação", "Histórico"],
);
add(
  "clinica",
  "comissoes",
  "Comissões",
  "Comercial",
  "finance",
  "Visão da atribuição e das etapas de apuração.",
  "23.3–23.4",
  "journey",
  ["Apuração", "Referência"],
  [],
  ["Atribuição", "Regra aprovada", "Apuração", "Revisão"],
);
add(
  "clinica",
  "protocolos",
  "Protocolos",
  "Acompanhamento",
  "protocols",
  "Estruture o acompanhamento; aptidão é uma decisão médica.",
  "32",
  "journey",
  ["Nome da estrutura", "Objetivo e etapas"],
  ["Estrutura de demonstração"],
  ["Composição", "Consulta de avaliação", "Decisão médica", "Acompanhamento"],
  "Explorar estrutura",
);
add(
  "clinica",
  "jornadas",
  "Jornadas",
  "Acompanhamento",
  "protocols",
  "Etapas, responsáveis e próximos passos do acompanhamento.",
  "30.1–30.2",
  "board",
  ["Jornada", "Etapas e responsáveis"],
  ["Jornada de implantação", "Jornada de relacionamento"],
  ["Entrada", "Em acompanhamento", "Concluído"],
  "Explorar jornada",
);
add(
  "clinica",
  "retencao",
  "Relacionamento",
  "Acompanhamento",
  "health",
  "Organize contatos de relacionamento sem usar dados clínicos para venda.",
  "30.4",
  "board",
  ["Contato", "Próxima ação administrativa"],
  ["Contato de boas-vindas", "Contato de acompanhamento"],
  ["Entrada", "Em acompanhamento", "Concluído"],
  "Explorar contato",
);
add(
  "clinica",
  "dispositivos",
  "Dispositivos",
  "Configurações",
  "devices",
  "Vínculos, estoque local e estado das conexões.",
  "25.5, 27.4",
  "connection",
  ["Dispositivo", "Vínculo"],
  [],
  ["Recebimento", "Identificação", "Vínculo", "Monitoramento"],
);
add(
  "clinica",
  "integracoes",
  "Integrações",
  "Configurações",
  "integrations",
  "Organize os serviços da clínica e acompanhe a conexão.",
  "22",
  "connection",
  ["Serviço", "Finalidade"],
  [],
  ["Serviço aprovado", "Configuração segura", "Validação", "Ativação"],
);
add(
  "clinica",
  "academy",
  "Academy",
  "Conteúdo",
  "graduation",
  "Trilhas de capacitação para sua equipe.",
  "16",
  "content",
  ["Trilha", "Resumo"],
  ["Conhecendo a plataforma", "Organização da clínica"],
  ["Trilha", "Conteúdo", "Progresso"],
);

add(
  "medico",
  "pacientes",
  "Pacientes",
  "Atendimento",
  "users",
  "Encontre pacientes vinculados à clínica selecionada.",
  "3.5, 5",
  "directory",
  ["Paciente", "Histórico"],
  ["Paciente de demonstração A", "Paciente de demonstração B"],
  ["Paciente correto", "Vínculo autorizado", "Histórico clínico"],
);
add(
  "medico",
  "consultas",
  "Consultas e prontuário",
  "Atendimento",
  "consultations",
  "Autoria, evoluções definitivas e histórico da consulta.",
  "3.2, 7",
  "journey",
  ["Consulta", "Registro"],
  [],
  ["Consulta autorizada", "Evolução", "Registro definitivo", "Nova evolução"],
);
add(
  "medico",
  "exames",
  "Exames e documentos",
  "Atendimento",
  "protocols",
  "Documentos, origem e revisão pelo profissional.",
  "3.4",
  "connection",
  ["Documento", "Origem"],
  [],
  ["Envio protegido", "Identificação", "Revisão", "Histórico"],
);
add(
  "medico",
  "resumo",
  "Preparação da consulta",
  "Atendimento",
  "sparkles",
  "Um espaço para reunir fontes e pontos da consulta.",
  "30.3",
  "journey",
  ["Resumo", "Fontes"],
  [],
  ["Fontes verificáveis", "Revisão profissional", "Consulta"],
);
add(
  "medico",
  "mensagens",
  "Mensagens e vídeo",
  "Comunicação",
  "share",
  "Canais de contato com o paciente dentro do vínculo autorizado.",
  "3.6",
  "connection",
  ["Conversa", "Participantes"],
  [],
  ["Identificação", "Vínculo", "Canal disponível"],
);

add(
  "app",
  "saude",
  "Minha saúde",
  "Acompanhamento",
  "health",
  "Histórico, exames e dados reunidos em um só lugar.",
  "8.1–8.2",
  "journey",
  ["Registro", "Origem"],
  [],
  ["Histórico", "Exames", "Dados disponíveis", "Revisão profissional"],
);
add(
  "app",
  "bioimpedancia",
  "Bioimpedância",
  "Acompanhamento",
  "activity",
  "Medições com origem e identificação corretas.",
  "27",
  "connection",
  ["Medição", "Origem"],
  [],
  ["Identificação", "Medição", "Histórico", "Revisão"],
);
add(
  "app",
  "protocolos",
  "Meu acompanhamento",
  "Acompanhamento",
  "protocols",
  "Etapas do protocolo liberado após avaliação médica.",
  "32",
  "journey",
  ["Protocolo", "Etapas"],
  [],
  ["Consulta inicial", "Avaliação médica", "Liberação", "Acompanhamento"],
);
add(
  "app",
  "hidratacao",
  "Hidratação",
  "Rotina",
  "day",
  "Um espaço para registrar água e acompanhar uma meta definida.",
  "8.3",
  "journey",
  ["Registro", "Quantidade"],
  [],
  ["Meta definida", "Registro", "Progresso"],
);
add(
  "app",
  "medicamentos",
  "Medicamentos",
  "Rotina",
  "health",
  "Lembretes da rotina prescrita, sem alterar sua orientação profissional.",
  "8.4",
  "journey",
  ["Lembrete", "Orientação"],
  [],
  ["Orientação profissional", "Rotina", "Lembrete", "Registro de adesão"],
);
add(
  "app",
  "habitos",
  "Hábitos e metas",
  "Rotina",
  "sparkles",
  "Pequenos passos e progresso, com critérios ainda a configurar.",
  "8.6, 31.4",
  "journey",
  ["Meta", "Próximo passo"],
  [],
  ["Meta", "Pequeno passo", "Progresso", "Revisão"],
);
add(
  "app",
  "alimentacao",
  "Alimentação",
  "Rotina",
  "day",
  "Registro de refeições e histórico para acompanhamento.",
  "8.8",
  "connection",
  ["Registro", "Descrição"],
  [],
  ["Registro", "Origem", "Análise disponível", "Histórico"],
);
add(
  "app",
  "treinos",
  "Treinos",
  "Rotina",
  "activity",
  "Sua organização de treinos e registros de atividade.",
  "8.9",
  "journey",
  ["Treino", "Orientação"],
  [],
  ["Plano orientado", "Atividade", "Registro", "Histórico"],
);
add(
  "app",
  "blog",
  "Blog",
  "Conteúdo",
  "book",
  "Conteúdo editorial selecionado para você.",
  "15",
  "content",
  ["Conteúdo", "Resumo"],
  ["Conheça a plataforma", "Organize seu acompanhamento"],
  ["Conteúdo", "Leitura", "Favoritos"],
);
add(
  "app",
  "beneficios",
  "Benefícios",
  "Serviços",
  "benefits",
  "Consulte o que está incluído no seu plano.",
  "8.7",
  "content",
  ["Benefício", "Condições"],
  ["Benefício de demonstração A", "Benefício de demonstração B"],
  ["Plano contratado", "Disponibilidade", "Agendamento"],
);
add(
  "app",
  "loja",
  "Loja",
  "Serviços",
  "sales",
  "Explore as ofertas disponibilizadas pela clínica.",
  "9.2",
  "content",
  ["Oferta", "Descrição"],
  ["Oferta de demonstração"],
  ["Catálogo", "Condições", "Adesão"],
);
add(
  "app",
  "dependentes",
  "Dependentes",
  "Serviços",
  "users",
  "Estrutura para vínculos familiares e permissões individuais.",
  "18",
  "directory",
  ["Dependente", "Vínculo familiar"],
  [],
  ["Identificação", "Vínculo", "Permissões aprovadas"],
);
add(
  "app",
  "financeiro",
  "Meu plano e pagamentos",
  "Serviços",
  "finance",
  "Plano ativo, histórico financeiro e condições de upgrade.",
  "19",
  "journey",
  ["Plano", "Condições"],
  [],
  ["Plano ativo", "Histórico", "Situação financeira", "Upgrade"],
);
add(
  "app",
  "indicacoes",
  "Indique e Ganhe",
  "Serviços",
  "share",
  "Acompanhe suas indicações conforme regras da clínica.",
  "17",
  "journey",
  ["Indicação", "Situação"],
  [],
  ["Regras da clínica", "Indicação", "Verificação", "Recompensa"],
);
add(
  "app",
  "consulta",
  "Preparar consulta",
  "Cuidado",
  "calendar",
  "Organize perguntas e informações para conversar com o profissional.",
  "31.2",
  "journey",
  ["Pergunta", "Contexto"],
  [],
  ["Motivo", "Perguntas", "Informações disponíveis", "Consulta"],
);
add(
  "app",
  "linha-do-tempo",
  "Linha do tempo",
  "Cuidado",
  "calendar",
  "Seus registros em contexto, sem conclusões automáticas.",
  "31.3",
  "journey",
  ["Registro", "Origem"],
  [],
  ["Registros", "Contexto", "Histórico"],
);
add(
  "app",
  "mensagens",
  "Mensagens",
  "Cuidado",
  "share",
  "Contato com o profissional e espaço de assistência por IA.",
  "8.5",
  "connection",
  ["Conversa", "Participantes"],
  [],
  ["Vínculo", "Canal disponível", "Conversa"],
);
add(
  "app",
  "privacidade",
  "Minha privacidade",
  "Cuidado",
  "shield",
  "Acessos, autorizações e solicitações sobre seus dados.",
  "31.5",
  "journey",
  ["Solicitação", "Escopo"],
  [],
  ["Acessos", "Autorizações", "Solicitação", "Resposta"],
);

export const moduleCatalog = modules;
export function moduleSpec(area: Area, slug: string) {
  return moduleCatalog.find((item) => item.area === area && item.slug === slug);
}
