/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StausRouteImport } from './routes/staus'
import { Route as ApiAccessCheckRouteImport } from './routes/api/access-check'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSectionRouteImport } from './routes/app.$section'
import { Route as ClinicaIndexRouteImport } from './routes/clinica.index'
import { Route as ClinicaSectionRouteImport } from './routes/clinica.$section'
import { Route as MedicoIndexRouteImport } from './routes/medico.index'
import { Route as MedicoSectionRouteImport } from './routes/medico.$section'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminSectionRouteImport } from './routes/super-admin.$section'
import { Route as ApiPlatformAuditRouteImport } from './routes/api/platform/audit'
import { Route as ApiPlatformClinicRouteImport } from './routes/api/platform/clinic'
import { Route as ApiPlatformClinicsRouteImport } from './routes/api/platform/clinics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StausRoute = StausRouteImport.update({
  id: '/staus',
  path: '/staus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessCheckRoute = ApiAccessCheckRouteImport.update({
  id: '/api/access-check',
  path: '/api/access-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSectionRoute = AppSectionRouteImport.update({
  id: '/app/$section',
  path: '/app/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaIndexRoute = ClinicaIndexRouteImport.update({
  id: '/clinica/',
  path: '/clinica/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaSectionRoute = ClinicaSectionRouteImport.update({
  id: '/clinica/$section',
  path: '/clinica/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoIndexRoute = MedicoIndexRouteImport.update({
  id: '/medico/',
  path: '/medico/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoSectionRoute = MedicoSectionRouteImport.update({
  id: '/medico/$section',
  path: '/medico/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSectionRoute = SuperAdminSectionRouteImport.update({
  id: '/super-admin/$section',
  path: '/super-admin/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformAuditRoute = ApiPlatformAuditRouteImport.update({
  id: '/api/platform/audit',
  path: '/api/platform/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformClinicRoute = ApiPlatformClinicRouteImport.update({
  id: '/api/platform/clinic',
  path: '/api/platform/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformClinicsRoute = ApiPlatformClinicsRouteImport.update({
  id: '/api/platform/clinics',
  path: '/api/platform/clinics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staus': typeof StausRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/app/$section': typeof AppSectionRoute
  '/clinica/$section': typeof ClinicaSectionRoute
  '/medico/$section': typeof MedicoSectionRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
  '/app/': typeof AppIndexRoute
  '/clinica/': typeof ClinicaIndexRoute
  '/medico/': typeof MedicoIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/platform/audit': typeof ApiPlatformAuditRoute
  '/api/platform/clinic': typeof ApiPlatformClinicRoute
  '/api/platform/clinics': typeof ApiPlatformClinicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staus': typeof StausRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/app/$section': typeof AppSectionRoute
  '/clinica/$section': typeof ClinicaSectionRoute
  '/medico/$section': typeof MedicoSectionRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
  '/app': typeof AppIndexRoute
  '/clinica': typeof ClinicaIndexRoute
  '/medico': typeof MedicoIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/api/platform/audit': typeof ApiPlatformAuditRoute
  '/api/platform/clinic': typeof ApiPlatformClinicRoute
  '/api/platform/clinics': typeof ApiPlatformClinicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staus': typeof StausRoute
  '/api/access-check': typeof ApiAccessCheckRoute
  '/app/$section': typeof AppSectionRoute
  '/clinica/$section': typeof ClinicaSectionRoute
  '/medico/$section': typeof MedicoSectionRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
  '/app/': typeof AppIndexRoute
  '/clinica/': typeof ClinicaIndexRoute
  '/medico/': typeof MedicoIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/platform/audit': typeof ApiPlatformAuditRoute
  '/api/platform/clinic': typeof ApiPlatformClinicRoute
  '/api/platform/clinics': typeof ApiPlatformClinicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/staus'
    | '/api/access-check'
    | '/app/$section'
    | '/clinica/$section'
    | '/medico/$section'
    | '/super-admin/$section'
    | '/app/'
    | '/clinica/'
    | '/medico/'
    | '/super-admin/'
    | '/api/platform/audit'
    | '/api/platform/clinic'
    | '/api/platform/clinics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/staus'
    | '/api/access-check'
    | '/app/$section'
    | '/clinica/$section'
    | '/medico/$section'
    | '/super-admin/$section'
    | '/app'
    | '/clinica'
    | '/medico'
    | '/super-admin'
    | '/api/platform/audit'
    | '/api/platform/clinic'
    | '/api/platform/clinics'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/staus'
    | '/api/access-check'
    | '/app/$section'
    | '/clinica/$section'
    | '/medico/$section'
    | '/super-admin/$section'
    | '/app/'
    | '/clinica/'
    | '/medico/'
    | '/super-admin/'
    | '/api/platform/audit'
    | '/api/platform/clinic'
    | '/api/platform/clinics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StausRoute: typeof StausRoute
  ApiAccessCheckRoute: typeof ApiAccessCheckRoute
  AppSectionRoute: typeof AppSectionRoute
  ClinicaSectionRoute: typeof ClinicaSectionRoute
  MedicoSectionRoute: typeof MedicoSectionRoute
  SuperAdminSectionRoute: typeof SuperAdminSectionRoute
  AppIndexRoute: typeof AppIndexRoute
  ClinicaIndexRoute: typeof ClinicaIndexRoute
  MedicoIndexRoute: typeof MedicoIndexRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  ApiPlatformAuditRoute: typeof ApiPlatformAuditRoute
  ApiPlatformClinicRoute: typeof ApiPlatformClinicRoute
  ApiPlatformClinicsRoute: typeof ApiPlatformClinicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staus': {
      id: '/staus'
      path: '/staus'
      fullPath: '/staus'
      preLoaderRoute: typeof StausRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access-check': {
      id: '/api/access-check'
      path: '/api/access-check'
      fullPath: '/api/access-check'
      preLoaderRoute: typeof ApiAccessCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$section': {
      id: '/app/$section'
      path: '/app/$section'
      fullPath: '/app/$section'
      preLoaderRoute: typeof AppSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica/': {
      id: '/clinica/'
      path: '/clinica'
      fullPath: '/clinica/'
      preLoaderRoute: typeof ClinicaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica/$section': {
      id: '/clinica/$section'
      path: '/clinica/$section'
      fullPath: '/clinica/$section'
      preLoaderRoute: typeof ClinicaSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico/': {
      id: '/medico/'
      path: '/medico'
      fullPath: '/medico/'
      preLoaderRoute: typeof MedicoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico/$section': {
      id: '/medico/$section'
      path: '/medico/$section'
      fullPath: '/medico/$section'
      preLoaderRoute: typeof MedicoSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/$section': {
      id: '/super-admin/$section'
      path: '/super-admin/$section'
      fullPath: '/super-admin/$section'
      preLoaderRoute: typeof SuperAdminSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/audit': {
      id: '/api/platform/audit'
      path: '/api/platform/audit'
      fullPath: '/api/platform/audit'
      preLoaderRoute: typeof ApiPlatformAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/clinic': {
      id: '/api/platform/clinic'
      path: '/api/platform/clinic'
      fullPath: '/api/platform/clinic'
      preLoaderRoute: typeof ApiPlatformClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/clinics': {
      id: '/api/platform/clinics'
      path: '/api/platform/clinics'
      fullPath: '/api/platform/clinics'
      preLoaderRoute: typeof ApiPlatformClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StausRoute: StausRoute,
  ApiAccessCheckRoute: ApiAccessCheckRoute,
  AppSectionRoute: AppSectionRoute,
  ClinicaSectionRoute: ClinicaSectionRoute,
  MedicoSectionRoute: MedicoSectionRoute,
  SuperAdminSectionRoute: SuperAdminSectionRoute,
  AppIndexRoute: AppIndexRoute,
  ClinicaIndexRoute: ClinicaIndexRoute,
  MedicoIndexRoute: MedicoIndexRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  ApiPlatformAuditRoute: ApiPlatformAuditRoute,
  ApiPlatformClinicRoute: ApiPlatformClinicRoute,
  ApiPlatformClinicsRoute: ApiPlatformClinicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
